// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuylmrohrbzygrlfowuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1eWxtcm9ocmJ6eWdybGZvd3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzYwOTUsImV4cCI6MjA3MTIxMjA5NX0.ax1zrF4xW9Cpwsli94jPvPNbWTtGYu2rrkf7c6VjNDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});